version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  cooldown:
    default-days: 7
- package-ecosystem: npm
  directory: /
  schedule:
    interval: monthly
  groups:
    security-fix:
      applies-to: security-updates
      patterns:
      - '*'
    minors:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
  cooldown:
    default-days: 7
