LIB=/usr/web/estpolis
IDIR=include
IFILES=\
	u.i\
	nav.i\
	link.i\
	linknav.i\

DIRS=\
	boss\
	char\
	doc\
	item\
	link\
	magic\
	map\
	monster\
	story\
	stuff\

WFFLAGS=-lja -x w html -x map svg
#MAPFLAGS=-v

PAGE=`{lspart $LSFLAGS $DB}

world:V:
	mk $MKFLAGS all 'DB=story'
	mk $MKFLAGS all 'DB=doc'
	mk $MKFLAGS all 'DB=char'
	mk $MKFLAGS all 'DB=item'
	mk $MKFLAGS all 'DB=magic'
	for(p in `{seq 0 2}){
		mk $MKFLAGS all 'DB=stuff' 'LSFLAGS=-D3 -P'$p
		mk $MKFLAGS all 'DB=map' 'LSFLAGS=-D3 -P'$p
		mk $MKFLAGS all 'DB=monster' 'LSFLAGS=-D3 -P'$p
	}
	for(p in `{ls map | grep -v '\.w$'})
		mk $MKFLAGS all 'DB='$p
	mk $MKFLAGS all 'DB=boss'
	mk $MKFLAGS all 'DB=link'
	mk $MKFLAGS all 'DB=lib'
	mk $MKFLAGS all 'DB=.'

<../mkweb
